# Generated by Django 4.2.3 on 2023-07-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(db_column='ID_AREA', primary_key=True, serialize=False)),
                ('nombre_area', models.CharField(db_column='NOMBRE_AREA', max_length=50)),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AtorizacionPermiso',
            fields=[
                ('id_autorizacion', models.AutoField(db_column='ID_AUTORIZACION', primary_key=True, serialize=False)),
                ('vehiculo', models.CharField(db_column='VEHICULO', max_length=50)),
                ('autorizacion_inicio', models.DateField(db_column='AUTORIZACION_INICIO')),
                ('autorizacion_fin', models.DateField(db_column='AUTORIZACION_FIN')),
            ],
            options={
                'db_table': 'atorizacion_permiso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CargaFamiliar',
            fields=[
                ('id_carga_familiar', models.AutoField(db_column='ID_CARGA_FAMILIAR', primary_key=True, serialize=False)),
                ('cf_nombre', models.CharField(blank=True, db_column='CF_NOMBRE', max_length=50, null=True)),
                ('parentesco', models.CharField(blank=True, db_column='PARENTESCO', max_length=40, null=True)),
                ('cf_sexo', models.CharField(blank=True, db_column='CF_SEXO', max_length=9, null=True)),
            ],
            options={
                'db_table': 'carga_familiar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(db_column='ID_CARGO', primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(db_column='NOMBRE_CARGO', max_length=50)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id_emergencia', models.AutoField(db_column='ID_EMERGENCIA', primary_key=True, serialize=False)),
                ('ce_nombre', models.CharField(db_column='CE_NOMBRE', max_length=50)),
                ('relacion_con_trabajador', models.CharField(db_column='RELACION_CON_TRABAJADOR', max_length=40)),
                ('ce_telefono', models.IntegerField(db_column='CE_TELEFONO')),
            ],
            options={
                'db_table': 'contacto_emergencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.AutoField(db_column='ID_CONTRATO', primary_key=True, serialize=False)),
                ('tipo_contrato', models.CharField(db_column='TIPO_CONTRATO', max_length=40)),
                ('contrato_inicio', models.DateField(db_column='CONTRATO_INICIO')),
                ('contrato_termino', models.DateField(db_column='CONTRATO_TERMINO')),
                ('archivo_contrato', models.TextField(db_column='ARCHIVO_CONTRATO')),
            ],
            options={
                'db_table': 'contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(db_column='ID_DEPARTAMENTO', primary_key=True, serialize=False)),
                ('departamento', models.CharField(db_column='DEPARTAMENTO', max_length=50)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluacionDesempeno',
            fields=[
                ('id_evaluacion', models.AutoField(db_column='ID_EVALUACION', primary_key=True, serialize=False)),
                ('tipo_evaluacion', models.CharField(db_column='TIPO_EVALUACION', max_length=50)),
                ('calificacion', models.IntegerField(db_column='CALIFICACION')),
                ('fecha_evaluacion', models.DateField(db_column='FECHA_EVALUACION')),
            ],
            options={
                'db_table': 'evaluacion_desempeno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id_liquidacion', models.AutoField(db_column='ID_LIQUIDACION', primary_key=True, serialize=False)),
                ('mes_liquidacion', models.DateField(blank=True, db_column='MES_LIQUIDACION', null=True)),
                ('archivo_liquidacion', models.TextField(blank=True, db_column='ARCHIVO_LIQUIDACION', null=True)),
            ],
            options={
                'db_table': 'liquidacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(db_column='ID_PERFIL', primary_key=True, serialize=False)),
                ('nombre_perfil', models.CharField(db_column='NOMBRE_PERFIL', max_length=50)),
            ],
            options={
                'db_table': 'perfil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroMedico',
            fields=[
                ('id_registro_medico', models.AutoField(db_column='ID_REGISTRO_MEDICO', primary_key=True, serialize=False)),
                ('tipo_registro_medico', models.CharField(db_column='TIPO_REGISTRO_MEDICO', max_length=50)),
                ('rm_fecha_ingreso', models.DateField(db_column='RM_FECHA_INGRESO')),
                ('rm_fecha_termino', models.DateField(db_column='RM_FECHA_TERMINO')),
                ('archivo_medico', models.TextField(db_column='ARCHIVO_MEDICO')),
            ],
            options={
                'db_table': 'registro_medico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('rut', models.CharField(db_column='RUT', max_length=16, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=50)),
                ('sexo', models.CharField(db_column='SEXO', max_length=9)),
                ('direccion', models.CharField(db_column='DIRECCION', max_length=50)),
                ('telefono', models.IntegerField(db_column='TELEFONO')),
                ('fecha_ingreso', models.DateField(db_column='FECHA_INGRESO')),
            ],
            options={
                'db_table': 'trabajador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='ID_USUARIO', primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(db_column='NOMBRE_USUARIO', max_length=50)),
                ('password', models.CharField(db_column='PASSWORD', max_length=50)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VacacionLicencia',
            fields=[
                ('id_solicitud', models.AutoField(db_column='ID_SOLICITUD', primary_key=True, serialize=False)),
                ('tipo_solicitud', models.CharField(db_column='TIPO_SOLICITUD', max_length=10)),
                ('fecha_inicio', models.DateField(db_column='FECHA_INICIO')),
                ('fecha_fin', models.DateField(db_column='FECHA_FIN')),
                ('dias', models.IntegerField(db_column='DIAS')),
                ('estado', models.CharField(db_column='ESTADO', max_length=50)),
            ],
            options={
                'db_table': 'vacacion_licencia',
                'managed': False,
            },
        ),
    ]
